version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: esp32_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: esp_data
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: esp32_phpmyadmin
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql-db

volumes:
  db_data:
